version: "3"

volumes:
  mongo.data:
  redis.data:

services:
  mongo:
    image: mongo:4.2
    container_name: ${COMPOSE_PROJECT_NAME}.mongo.docker
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_NAME}
    volumes:
      - mongo.data:/data/db
    ports:
      - 127.0.0.1:${MONGO_PORT}:27017
    networks:
      - global

  redis:
    image: redis:5.0
    container_name: ${COMPOSE_PROJECT_NAME}.redis.docker
    restart: unless-stopped
    volumes:
      - redis.data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 127.0.0.1:${REDIS_PORT}:6379
    networks:
      - global

networks:
  global:
